# Generated by Django 3.2 on 2021-04-27 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_id', models.TextField(choices=[('0', 'SEE_STEP'), ('1', 'SUBMIT_STEP'), ('2', 'SOLVE_STEP')])),
                ('target_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='steps.steps')),
            ],
        ),
    ]
