# Generated by Django 3.2 on 2021-04-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='action_id',
            field=models.TextField(choices=[('0', 'SEEN'), ('1', 'SUBMITTED'), ('2', 'SOLVED')]),
        ),
    ]
