# Generated by Django 3.2 on 2021-04-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210428_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='target_id',
            new_name='target',
        ),
    ]
