# Generated by Django 3.2 on 2021-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_target_id_events_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='action_id',
            field=models.TextField(choices=[(0, 'SEEN'), (1, 'SUBMITTED'), (2, 'SOLVED')]),
        ),
    ]
